=== denisjacquemin/HubWorker/app/xsd/properties.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="property" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="refagent"/>
              <xs:element type="xs:string" name="title" minOccurs="0"/>
              <xs:element type="xs:string" name="description" minOccurs="0"/>
              <xs:element type="xs:float" name="price" minOccurs="0"/>
              <xs:element type="xs:string" name="address" minOccurs="0"/>
              <xs:element type="xs:byte" name="bedroom" minOccurs="0"/>
              <xs:element type="xs:anyURI" name="url" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="action" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== denisjacquemin/HubWorker/public/immo356/properties/properties_20150129190212.xml
<?xml version="1.0" encoding="UTF-8"?>
<properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="properties.xsd">
   <property action="create">
      <refagent>pr003</refagent>
      <title>titre 1</title>
      <description>description 1</description>
      <price>12345</price>
      <address>voici une adresse</address>
      <bedroom>2</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
   <property action="update">
      <refagent>dssdds</refagent>
      <title>titre 2</title>
      <description>description 2</description>
      <price>67890</price>
      <address>rue du chemin</address>
      <bedroom>3</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
   <property action="update">
      <refagent>pr0045</refagent>
      <title>titre 3</title>
      <description>description 3</description>
      <price>13579.45</price>
      <address>voici une adresse</address>
      <bedroom>3</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
   <property action="delete">
      <refagent>pr0045</refagent>
   </property>
</properties>

=== denisjacquemin/HubWorker/sample/properties_20150129190212.xml
<?xml version="1.0" encoding="UTF-8"?>
<properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="properties.xsd">
   <property>
      <title>titre 1</title>
      <description>description 1</description>
      <price>12345</price>
      <address>voici une adresse</address>
      <bedroom>2</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
   <property>
      <title>titre 2</title>
      <description>description 2</description>
      <price>67890</price>
      <address>rue du chemin</address>
      <bedroom>5</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
   <property>
      <title>titre 3</title>
      <description>description 3</description>
      <price>13579.45</price>
      <address>voici une adresse</address>
      <bedroom>3</bedroom>
      <url>http://www.example.com/bienavendre12</url>
   </property>
</properties>
